name = "oksend"
compatibility_date = "2024-10-01"
pages_build_output_dir = "dist"

# R2 bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "oksend-bucket"

# Optional: KV namespace for slug-based links
[[kv_namespaces]]
binding = "LINKS"
id = "2893e1a42c274e049f4a00fff10b0b37"

